import assert from "node:assert/strict";
import test from "node:test";
import { Check } from "typebox/value";
import { TelemetryCollector } from "../../pi-runtime/src/telemetry.ts";
import { RunProgressSchema, TelemetryTraceSchema } from "./telemetry.ts";
import { projectRunProgress, summarizeTelemetry } from "./telemetry-summary.ts";
test("shared telemetry summary preserves partial measurements and does not double-count nested spans", () => {
  const c = new TelemetryCollector({ operation: "answer", commandId: "cmd" });
  const agent = c.start("report_agent", "agent", undefined, { attempt: 1 });
  const first = c.start("model_request", "model", agent.spanId);
  c.finish(first, { usage: { input: 10, output: 4, cacheRead: 5, cacheWrite: 0 } }); first.durationMs = 100;
  const second = c.start("model_request", "model", agent.spanId); c.finish(second); second.durationMs = 200;
  c.finish(agent); agent.durationMs = 500;
  c.end("succeeded"); c.trace.durationMs = 600;
  const summary = summarizeTelemetry([c.trace]);
  assert.deepEqual(summary.inputTokens, { value: 10, availability: "partial", known: 1, total: 2 });
  assert.equal(summary.totalInputTokens.value, 15);
  assert.equal(summary.modelDurationSumMs.value, 300);
  assert.equal(summary.latency.p95Ms, 600);
  assert.equal(summary.providerRetryCount, 0);
  assert.equal(summary.modelRequestCount, 2);
  assert.ok(Check(TelemetryTraceSchema, c.trace));
});
test("terminal trace and safe progress are stable after errors, correction and repeated finalization", () => {
  const c = new TelemetryCollector({ operation: "answer", commandId: "cmd" });
  const events: string[] = [];
  c.subscribe((trace) => events.push(trace.status!));
  const agent = c.start("report_agent", "agent", undefined, { attempt: 2 });
  const tool = c.start("tool_call", "tool", agent.spanId);
  c.error(tool, "tool_error", new Error("SECRET candidate answer Authorization: Bearer KEY"));
  c.finish(tool); c.finish(agent); c.end("succeeded"); c.end("failed");
  assert.equal(c.trace.status, "succeeded");
  assert.equal(events.filter((status) => status === "succeeded").length, 1);
  const progress = projectRunProgress(c.trace);
  assert.ok(Check(RunProgressSchema, progress));
  assert.equal(progress.retryCount, 1);
  assert.doesNotMatch(JSON.stringify(c.trace), /SECRET|Authorization|KEY/);
  assert.doesNotMatch(JSON.stringify(progress), /tool_error|report_agent|sourceQuote/);
});
