import assert from "node:assert/strict";
import test from "node:test";
import { Check } from "typebox/value";
import { TelemetryCollector } from "../../pi-runtime/src/telemetry.ts";
import { RunProgressSchema, TelemetryTraceSchema } from "./telemetry.ts";
import { projectRunProgress, summarizeTelemetry } from "./telemetry-summary.ts";
test("shared telemetry summary preserves partial measurements and does not double-count nested spans", () => {
  const c = new TelemetryCollector({ operation: "answer", commandId: "cmd" });
  const agent = c.start("report_agent", "agent", undefined, { attempt: 1 });
  const first = c.start("model_request", "model", agent.spanId);
  c.finish(first, { usage: { input: 10, output: 4, cacheRead: 5, cacheWrite: 0 } }); first.durationMs = 100;
  const second = c.start("model_request", "model", agent.spanId); c.finish(second); second.durationMs = 200;
  c.finish(agent); agent.durationMs = 500;
  c.end("succeeded"); c.trace.durationMs = 600;
  const summary = summarizeTelemetry([c.trace]);
  assert.deepEqual(summary.inputTokens, { value: 10, availability: "partial", known: 1, total: 2 });
  assert.equal(summary.totalInputTokens.value, 15);
  assert.equal(summary.modelDurationSumMs.value, 300);
  assert.equal(summary.latency.p95Ms, 600);
  assert.equal(summary.providerRetryCount, 0);
  assert.equal(summary.modelRequestCount, 2);
  assert.ok(Check(TelemetryTraceSchema, c.trace));
});
test("terminal trace and safe progress are stable after errors, correction and repeated finalization", () => {
  const c = new TelemetryCollector({ operation: "answer", commandId: "cmd" });
  const events: string[] = [];
  c.subscribe((trace) => events.push(trace.status!));
  const agent = c.start("report_agent", "agent", undefined, { attempt: 2 });
  const tool = c.start("tool_call", "tool", agent.spanId);
  c.error(tool, "tool_error", new Error("SECRET candidate answer Authorization: Bearer KEY"));
  c.finish(tool); c.finish(agent); c.end("succeeded"); c.end("failed");
  assert.equal(c.trace.status, "succeeded");
  assert.equal(events.filter((status) => status === "succeeded").length, 1);
  const progress = projectRunProgress(c.trace);
  assert.ok(Check(RunProgressSchema, progress));
  assert.equal(progress.retryCount, 1);
  assert.doesNotMatch(JSON.stringify(c.trace), /SECRET|Authorization|KEY/);
  assert.doesNotMatch(JSON.stringify(progress), /tool_error|report_agent|sourceQuote/);
});
test("trajectory preserves ordered starts, completion, rejected tools and recovery without exposing raw logs", () => {
  const c = new TelemetryCollector({ operation: "answer" });
  const snapshots: ReturnType<typeof projectRunProgress>[] = [];
  c.subscribe((trace) => snapshots.push(projectRunProgress(trace)));
  const agent = c.start("report_agent", "agent");
  const model = c.start("model_request", "model", agent.spanId);
  let step = projectRunProgress(c.trace, Date.parse(model.startedAt) + 2300).steps!.at(-1)!;
  assert.equal(step.runningLabel, "正在思考如何补充报告");
  assert.equal(step.status, "running"); assert.equal(step.elapsedMs, 2300); assert.equal(step.parentId, agent.spanId);
  c.finish(model); model.durationMs = 9390;
  step = projectRunProgress(c.trace).steps!.at(-1)!;
  assert.equal(step.status, "succeeded"); assert.equal(step.elapsedMs, 9390);
  const tool = c.start("tool_call", "tool", agent.spanId, { toolName: "edit_report" });
  c.finish(tool, { outcome: "rejected" });
  assert.equal(projectRunProgress(c.trace).steps!.at(-1)!.status, "rejected");
  const repaired = c.start("tool_call", "tool", agent.spanId, { toolName: "edit_report" });
  c.finish(repaired); c.finish(agent); c.end("succeeded");
  const progress = projectRunProgress(c.trace);
  assert.equal(progress.steps!.length, 4);
  assert.deepEqual(progress.steps!.map((s) => s.status), ["succeeded", "succeeded", "rejected", "succeeded"]);
  assert.ok(snapshots.some((p) => p.steps!.at(-1)?.id === model.spanId && p.steps!.at(-1)?.status === "running"));
  assert.ok(Check(RunProgressSchema, progress));
  assert.doesNotMatch(JSON.stringify(progress), /report_agent|model_request|edit_report|sourceQuote/);
});
test("retrieval fallback is not shown as successful retrieval and nested implementation spans stay in developer details", () => {
  const c = new TelemetryCollector();
  const tool = c.start("tool_call", "tool", undefined, { toolName: "retrieve_probe_knowledge" });
  const retrieval = c.start("retrieve_probe_knowledge", "retrieval", tool.spanId, { retrieval: { query: "PRIVATE_QUERY", hits: [], referencedIds: [], fallback: "static_playbook" } });
  const embedding = c.start("query_embedding", "embedding", retrieval.spanId);
  c.finish(embedding, { status: "failed" }); c.finish(retrieval); c.finish(tool); c.end("succeeded");
  const progress = projectRunProgress(c.trace);
  assert.equal(progress.steps!.length, 1);
  assert.equal(progress.steps![0].status, "fallback");
  assert.match(progress.steps![0].label, /改用/);
  assert.doesNotMatch(JSON.stringify(progress), /PRIVATE_QUERY|query_embedding/);
});
